### ISSUE TITLE
cannot download dataset qidpidtriples.train.full.tar.gz

### ISSUE THREAD

**Issue by yixuan-qiao** [microsoft/TREC-2019-Deep-Learning#14]
when download this file, following problems arises, same as TREC-2020-Deep-Learning

![image](https://user-images.githubusercontent.com/25563825/82975388-e4648280-a00e-11ea-9100-ebea43e6a7bc.png)

**Comment by bhaskar-mitra** [comment]
Sorry, the correct filename should have been qidpidtriples.train.full.```tsv```.gz. I've fixed the link now. Can you please retry?

**Comment by yixuan-qiao** [comment]
thanks, it is working now. :-)

**Comment by bhaskar-mitra** [comment]
Awesome, glad that worked! I will close this issue then.

**Comment by bhaskar-mitra** [comment]
Btw, small note: you should look at the updated guidelines for TREC 2020 Deep Learning track for the latest data.
https://microsoft.github.io/TREC-2020-Deep-Learning/

**Comment by amirsoto** [comment]
hello :
Please you can show me how to run this 
((https://github.com/sekilab/RoadDamageDetector/ )) 
on windows
thank you
