### ISSUE TITLE
How did you calculate the score for document and query?

### ISSUE THREAD

**Issue by Dinesh-Mali** [microsoft/TREC-2019-Deep-Learning#5]
In top 100 doc for train queries, you have given rank and related score. 
How did you calculated that score? is a score based on rank only, or is it based on document and query relevance?
which features have you considered for estimating the scores and ranking for documents?
Please guide, thanks.

**Comment by eminey** [comment]
Hi Dinesh,

We used a very basic IR model to generate the rankings and the scores.

Best,
Emine

**Comment by Dinesh-Mali** [comment]
Thanks @eminey .
