### ISSUE TITLE
Mandatory participation in both tasks?

### ISSUE THREAD

**Issue by Manajit89** [microsoft/TREC-2019-Deep-Learning#7]
Hello organizers,

Do we have to participate in both the `Document Ranking` and `Passage Ranking` tasks under Deep Learning track or can we participate in any one of them? The guidelines are not clear on this. Also, as @lintool pointed, it is not clear how many runs are we allowed to submit.

Also, it would be nice of you to provide a mailing list or email address where we can post our queries pertaining to this track. As of now, the website has no contact details.

Thanks,
Manajit

**Comment by bhaskar-mitra** [comment]
Hi Manajit,

You are allowed to take part in either or both tasks (document ranking and passage ranking). You can submit up to three runs for each of these tasks. We've updated the guidelines to reflect these.

Best regards,
Bhaskar

**Comment by Manajit89** [comment]
Thank you very much!

Manajit
